baseURL = "https://example.github.io/malware-blog/"
languageCode = "en-us"
title = "SGdbg"
theme = "carbon"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  author = "Shruti Gurlhosur"
  #handle = "@SGdbg"
  tagline = "Experimenting with Malware analysis & reverse engineering by getting hands dirty"
  linkedin = "https://www.linkedin.com/in/shruti-gurlhosur/"
  github = "https://github.com/ShrutiGurlhosur"
  twitter = "https://x.com/shrutigurlhosur"
  email = "shruti.gurlhosur@gmail.com"
  accent = "#3fb950"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    style = "github-dark"
    lineNos = true
    codeFences = true
    guessSyntax = true
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 2
  [[menu.main]]
    name = "YARA Rules"
    url = "/yara-rules/"
    weight = 3
  [[menu.main]]
    name = "Scripts"
    url = "/scripts/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[outputs]
  home = ["HTML", "RSS"]
